language: node_js

node_js:
    - "4.1"
    #- "4.0"
    #- "0.12"
    #- "0.11"
    #- "0.10"



sudo: false



git:
    submodules: false



addons:
    apt:
        packages:
            #- php-codesniffer
            #- phpmd
            #- shellcheck



before_script:

    # Create a build directory for output
    # Store all files in your own bin
    #- install --directory build/bin
    #- install --directory build/webroot
    #- export PATH=$PATH:$PWD/build/bin/

    # Install validation tools
    #- npm install -g htmlhint csslint jshint jscs jsonlint js-yaml html-minifier@0.8.0 clean-css uglify-js

    # Install using makefile
    - make npm-install



script:
    # Check versions of validation tools
    #- node --version
    #- npm --version
    
    #- htmlhint --version
    #- csslint --version
    #- jscs --version
    #- jshint --version
    #- jsonlint --version
    #- js-yaml --version
    
    #- html-minifier --version
    #- cleancss --version
    #- uglifyjs --version
    
    # Run tests
    - make npm-version
    - make test



notifications:
    irc: "irc.freenode.org#dbwebb"

    webhooks:
        urls:
            - https://webhooks.gitter.im/e/b46f664da8f9fad41891

        # options: [always|never|change] default: always
        on_success: change
        on_failure: always
        on_start: never
